### ISSUE TITLE
Japanese version of "Share an app" section is a bit old 

### ISSUE THREAD

**Issue by damedom** [MicrosoftDocs/powerapps-docs.ja-jp#5]
Japanese version of "Share an app" section is a bit old : https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/share-app

There's no longer "+Add everyone in my org" when sharing apps. Instead of that, we should type "Everyone" in the search box. English version describes this correctly but Japanese version doesn't.

English: 
=================================================

> 4. Specify by name or alias the users or security groups in Azure Active Directory with which you want to share the app.
> To allow your entire organization to run the app (but not modify or share it), type Everyone in the sharing panel.
> ![image](https://user-images.githubusercontent.com/2128506/53317490-29cb6900-390f-11e9-8bf9-a2dd9586065e.png)

Japanese:
=================================================

> 3. アプリを共有する Azure Active Directory のユーザーまたはセキュリティ グループで指定します。
>  注意
> 組織内の配布グループ、または組織外のユーザーまたはグループとアプリを共有することはできません。
> [Screenshot with "+Add everyone in my org" button]
![image](https://user-images.githubusercontent.com/2128506/53317480-1fa96a80-390f-11e9-8ceb-6e9956fee9d9.png)
> アプリを実行できるように組織全体とアプリを共有することもできますが、そのようにして共有を受けたユーザーはアプリを変更したり他のユーザーと共有したりすることはできません。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 60fb8dba-da1c-6845-d301-c3b18a6b98ef
* Version Independent ID: a5d1fd66-fe5b-f52d-47de-6af3c71928f7
* Content: [キャンバス アプリを共有する - PowerApps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/share-app#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/share-app.md](https://github.com/MicrosoftDocs/powerapps-docs.ja-jp/blob/live/powerapps-docs/maker/canvas-apps/share-app.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by CeciAc** [comment]
Hello, @damedom 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by Alisha-Acharya** [comment]
This issue is resolved now. Thanks !
