### ISSUE TITLE
[LOC] "「こんにちは, world」" needs to be replaced with "Hello, world"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/powerapps-docs.ja-jp#52]
https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/add-configure-controls

![add-configure-controls_j](https://user-images.githubusercontent.com/40815708/61580768-4a12f300-ab50-11e9-9efb-32ee4059d649.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 53616064-ae0b-0569-4a56-f4cdf8dd2cbf
* Version Independent ID: cf3299c3-6840-c8eb-f820-567951798905
* Content: [キャンバス アプリ コントロールを追加および構成する - PowerApps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/add-configure-controls)
* Content Source: [powerapps-docs/maker/canvas-apps/add-configure-controls.md](https://github.com/MicrosoftDocs/powerapps-docs.ja-jp/blob/live/powerapps-docs/maker/canvas-apps/add-configure-controls.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by hyoshioka0128** [comment]
Duplicate: "https://github.com/MicrosoftDocs/powerapps-docs.ja-jp/pull/55"
Close: #52
