### ISSUE TITLE
誤訳（乃至は不適切な訳語選択）

### ISSUE THREAD

**Issue by FumioNakamura** [MicrosoftDocs/powerapps-docs.ja-jp#66]
説明の項目で、『空白関数』や『合体関数』の訳語が使われていますが、これらは本来訳すべきでないと思います。
本来の関数名をそのまま記載すべきでしょう。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: afe9fac7-f56e-31c7-ef09-bc0baa5570ea
* Version Independent ID: 2025e0c3-918e-612a-3138-ae5617adb809
* Content: [Blank、Coalesce、IsBlank、および IsEmpty 関数 - PowerApps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/functions/function-isblank-isempty#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/functions/function-isblank-isempty.md](https://github.com/MicrosoftDocs/powerapps-docs.ja-jp/blob/live/powerapps-docs/maker/canvas-apps/functions/function-isblank-isempty.md)
* Service: **powerapps**
* GitHub Login: @gregli-msft
* Microsoft Alias: **gregli**

**Comment by srvbpigh** [comment]
Hello, @FumioNakamura
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@FumioNakamura

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/functions/function-isblank-isempty#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
