### ISSUE TITLE
誤字

### ISSUE THREAD

**Issue by ayunum** [MicrosoftDocs/powerapps-docs.ja-jp#67]
ユーザーを認証する - ユーザーが以前にアプリを開いたことが名井場合⇒無い場合

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: af7d6ebf-7d17-44ef-4348-354a8332081b
* Version Independent ID: 8427e65c-bf62-86c4-89b8-ecf5f59a890e
* Content: [キャンバス アプリのパフォーマンスを最適化する - PowerApps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/performance-tips#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/performance-tips.md](https://github.com/MicrosoftDocs/powerapps-docs.ja-jp/blob/live/powerapps-docs/maker/canvas-apps/performance-tips.md)
* Service: **powerapps**
* GitHub Login: @yingchin
* Microsoft Alias: **yingchin**

**Comment by srvbpigh** [comment]
Hello, @ayunum
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@ayunum

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/performance-tips#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
