### ISSUE TITLE
ツリービューでの操作

### ISSUE THREAD

**Issue by s-kawara** [MicrosoftDocs/powerapps-docs.ja-jp#8]
・Ctrl + [　
現　状：旧バージョンと、コントロールを送信します。
修正案：コントロールを背面へ移動します。

・Ctrl + Shift + [
現　状：バックアップに送信します。
修正案：最背面へ移動します。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 955cb34a-35ce-b369-a83b-b68195de2a63
* Version Independent ID: e7503f23-33ab-2a1a-6796-ea6d96b64146
* Content: [キャンバス アプリのキーボード ショートカット - PowerApps](https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/keyboard-shortcuts#feedback)
* Content Source: [powerapps-docs/maker/canvas-apps/keyboard-shortcuts.md](https://github.com/MicrosoftDocs/powerapps-docs.ja-jp/blob/live/powerapps-docs/maker/canvas-apps/keyboard-shortcuts.md)
* Service: **powerapps**
* GitHub Login: @AFTOwen
* Microsoft Alias: **anneta**

**Comment by CeciAc** [comment]
@s-kawara  様、
コメントをお寄せいただき、誠にありがとうございます。docs.microsoft.com におけるエクスペリエンスの改善に努めておりますが、お寄せいただいたフィードバックに従って対応するにあたり、さらに情報をいただけるならありがたく存じます。さらに詳しい情報とともに、コメントについてご説明いただけましたら幸いです。
敬具
Microsoft DOCS インターナショナル チーム

**Comment by CeciAc** [comment]
こんにちは、@s-kawara 様、

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@s-kawara

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/powerapps/maker/canvas-apps/keyboard-shortcuts#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
